# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='prefix'),
        ),
    ]
