# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincoach',
            name='coach_ptr',
        ),
        migrations.AddField(
            model_name='coach',
            name='is_main_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MainCoach',
        ),
    ]
