# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 09:56
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+31', max_length=128, verbose_name='phonenumber'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+31', max_length=128, verbose_name='phonenumber'),
        ),
    ]
