# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_detail', models.CharField(max_length=30, verbose_name='detail_name')),
            ],
            options={
                'verbose_name': 'Detail',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('food_preferences', models.CharField(blank=True, max_length=255)),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('wheelchair_bound', models.BooleanField(default=False, verbose_name='wheelchair bound')),
            ],
            options={
                'verbose_name': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='sport')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='SportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
    ]
