# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_detail', models.CharField(max_length=30, verbose_name='detail_name')),
            ],
            options={
                'verbose_name': 'Detail',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('food_preferences', models.CharField(blank=True, max_length=255)),
                ('wheelchair_bound', models.BooleanField(default=False, verbose_name='wheelchair bound')),
                ('photo_choice', models.BooleanField(default=True, verbose_name='Photography allowed')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
            options={
                'verbose_name': 'Participant',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='sport')),
                ('description', models.CharField(blank=True, max_length=150, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='SportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='value')),
                ('detail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sports.Detail')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
                ('team_members', models.ManyToManyField(related_name='team_members', to='sports.Participant')),
            ],
            options={
                'verbose_name': 'Team',
            },
        ),
        migrations.AddField(
            model_name='participant',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sport_details',
            field=models.ManyToManyField(blank=True, to='sports.SportDetail'),
        ),
        migrations.AddField(
            model_name='detail',
            name='sport',
            field=models.ManyToManyField(through='sports.SportDetail', to='sports.Sport'),
        ),
    ]
