# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='sport_details',
            field=models.ManyToManyField(to='sports.SportDetail'),
        ),
    ]
