# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('food_preferences', models.CharField(blank=True, max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+31', max_length=128, verbose_name='phonenumber')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('club', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
