# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Club'),
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(to='sports.Participant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Sport'),
        ),
        migrations.AddField(
            model_name='participant',
            name='sport_details',
            field=models.ManyToManyField(to='sports.SportDetail'),
        ),
    ]
