# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AddField(
            model_name='coach',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='prefix'),
        ),
        migrations.AddField(
            model_name='participant',
            name='prefix',
            field=models.CharField(blank=True, max_length=10, verbose_name='prefix'),
        ),
    ]
