# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20161014_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='photo_choice',
            field=models.BooleanField(default=True, verbose_name='Photo allowed'),
        ),
    ]
