# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_participant_photo_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='photo_choice',
            field=models.BooleanField(default=True, verbose_name='Photography allowed'),
        ),
    ]
