# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('street', models.CharField(max_length=128, verbose_name='street')),
                ('number', models.CharField(blank=True, max_length=10, verbose_name='number')),
                ('zipcode', models.CharField(max_length=6, verbose_name='zipcode')),
                ('city', models.CharField(max_length=30, verbose_name='city')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+31', max_length=128, verbose_name='phonenumber')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
    ]
